version: '2.1'
services:
  db:
    restart: always
    image: "bitnami/postgresql:11"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRESQL_PASSWORD=${DB_PWD}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - ./pg:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: "tokenchannel-keycloak:15-TC"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PWD}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
    ports:
      - "8081:8080"
      - "8000:8000" # debug
